services:
  app:
    container_name: ${APP_NAME}
    image: ghcr.io/cnpem/${IMAGE_NAME}:${IMAGE_VERSION}
    environment:
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_TRUST_HOST: 1
      BLUESKY_HTTPSERVER_URL: ${BLUESKY_HTTPSERVER_URL}
      PVWS_URL: ${PVWS_URL}
    restart: unless-stopped
    expose:
      - "3000"
    # ports:
    #   - 3000:3000
